base_global_planner: global_planner/GlobalPlanner

GlobalPlanner:
  allow_unknown: true
  default_tolerance: 1.0
  visualize_potential: false
  use_dijkstra: false
  use_quadratic: true
  use_grid_path: true
  old_navfn_behavior: false
  neutral_cost: 50
  outline_map: true
  cost_factor: 1